[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"

[compat]
Ferrite = "=1.3.0"

[sources]
ExplicitImports = {path = "../.."}
